{% set version = "1.14.0" %}

package:
  name: glue-core
  version: {{ version }}

source:

  fn: glue-core-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/glue-core/glue-core-{{ version }}.tar.gz
  sha256: 72b5ee83afcc859deaa4b270808a613d04b3ede426e4b5a35074645ee03393b2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=30.3
    - setuptools_scm
  run:
    - python >=3.8
    - astropy >=4.0
    - dill >=0.2
    - echo >=0.6
    - glue-qt >=0.1
    - h5py >=2.10
    - matplotlib-base >=3.2
    - mpl-scatter-density >=0.7
    - numpy >=1.17
    - pandas >=1.2
    - openpyxl >=3.0
    - scipy >=1.1
    - setuptools >=30.3
    - xlrd >=1.2
    - shapely >=2.0

    # Optional dependencies (defined in ``extras_require``)
    - scikit-image

    # Temporary: the scikit-image conda package is missing the dask dependency
    # so we add it here for now
    - dask

test:
  requires:
    - pip
  imports:
    - glue
    - glue.core
  commands:
    - pip check
    - glue --version

about:
  home: http://glueviz.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog
    - izahn
