{% set name = "glue-core" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/glue_core-{{ version }}.tar.gz
  sha256: d730bcd483eadf58cb566199a2012a95714075fb522077a1ea0420ef388cd45b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.17
    - matplotlib-base >=3.2
    - scipy >=1.1
    - pandas >=1.2
    - echo >=0.6
    - astropy >=4.0
    - fast-histogram >=0.12
    - setuptools >=30.3.0
    - ipython >=4.0
    - dill >=0.2
    - h5py >=2.10
    - xlrd >=1.2
    - openpyxl >=3.0
    - mpl-scatter-density >=0.7
    - pvextractor >=0.2
    - importlib-resources >=1.3
    - importlib-metadata >=3.6
    - shapely >=2.0

    # Optional dependencies (defined in ``extras_require``)
    - scikit-image

test:
  requires:
    - pip
    - pytest
  imports:
    - glue
    - glue.core
  commands:
    - pip check
    - pytest --pyargs glue

about:
  home: http://glueviz.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog
    - izahn
