{% set name = "glue-core" %}
{% set version = "1.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/glue_core-{{ version }}.tar.gz
  sha256: c36e5b5d73bcb28080afe8a98128affb0cd00ac1f3aa025ba76aec96c3113cdf

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.10
    - numpy >=1.17
    - matplotlib-base >=3.2
    - scipy >=1.1
    - pandas >=1.2
    - echo >=0.6
    - astropy-base >=4.0
    - fast-histogram >=0.12
    - ipython >=4.0
    - dill >=0.2
    - h5py >=2.10
    - xlrd >=1.2
    - openpyxl >=3.0
    - mpl-scatter-density >=0.8
    - importlib-resources >=1.3
    - importlib-metadata >=3.6
    - shapely >=2.0

    # Optional dependencies (defined in ``extras_require``)
    - scikit-image

test:
  requires:
    - pip
    - pytest
  imports:
    - glue
    - glue.core
  commands:
    - pip check
    - pytest --pyargs glue

about:
  home: http://glueviz.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog
    - izahn
