{% set version = "1.1.0" %}

package:
  name: glue-core
  version: {{ version }}

source:

  fn: glue-core-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/glue-core/glue-core-{{ version }}.tar.gz
  sha256: 38c33ad99b39b9112f4bd312fcaf9560a3deb503b69d121ba85d8293804d9ecd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - glue = glue.main:main
    - glue-config = glue.config_gen:main
    - glue-deps = glue._deps:main
  osx_is_app: true
  skip: true  # [py<37]
  
requirements:

  host:

    - python
    - pip
    - setuptools >=30.3
    - setuptools_scm

  run:

    # The following is needed to make sure that the package works as a GUI
    # application (glue needs to be run with python.app, not python)
    - python.app  # [osx]

    # Required dependencies
    - python
    - numpy >=1.17
    - matplotlib-base >=3.2
    - scipy >=1.1
    - pandas >=1.2
    - echo >=0.5
    - astropy >=4.0
    - setuptools >=30.3
    - qtpy >=1.9
    - ipython >=4.0
    - ipykernel >=4.0,!=5.0.0,!=5.1.0
    - qtconsole >=4.3
    - jupyter_client <7
    - dill >=0.2
    - xlrd >=1.2
    - openpyxl >=3.0
    - h5py >=2.10
    - mpl-scatter-density >=0.7
    - bottleneck >=1.3
    - pyqt

    # Optional dependencies (defined in ``extras_require``)
    - scikit-image

    # Temporary: the scikit-image conda package is missing the dask dependency
    # so we add it here for now
    - dask

test:
  imports:
    - glue
    - glue.core
    - glue.app.qt
  commands:
    - glue --version
    - glue-deps list

# NOTE: we deliberatey do NOT include an app entry here, because we instead do this
# in the glueviz meta-package (we don't want glue to appear twice in the navigator)

about:
  home: http://glueviz.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
