{% set version = "0.14.2" %}

package:
  name: glue-core
  version: {{version}}

source:

  fn: glue-core-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glue-core/glue-core-{{version}}.tar.gz
  sha256: 25e679a789ebc9d745ccb4cce75077763bd77fa92b8895b57c9c1ef23f4b969e

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - glue = glue.main:main
    - glue-config = glue.config_gen:main
    - glue-deps = glue._deps:main
  osx_is_app: True

requirements:

  build:
    - python
    - pip
    # We need to include PyQt5 here to make sure that PyQt5 doesn't
    # get included in install_requires
    - pyqt

  run:

    # The following is needed to make sure that the package works as a GUI
    # application (glue needs to be run with python.app, not python)
    - python.app  # [osx]

    # Required dependencies
    - python
    - numpy >=1.9
    - pandas >=0.14
    - astropy >=2.0
    - matplotlib >=2.0
    - qtpy >=1.2
    - ipython >=4.0
    - ipykernel
    - qtconsole
    - dill >=0.2
    - xlrd >=1.0
    - h5py >=2.4
    - bottleneck >=1.2
    - mpl-scatter-density >=0.4
    - setuptools >=1.0
    - pyqt

    # Optional dependencies (defined in ``extras_require``)
    - scipy
    - scikit-image
    - plotly

    # Temporary: the scikit-image conda package is missing the dask dependency
    # so we add it here for now
    - dask

test:
  imports:
    - glue
    - glue.core
    - glue.app.qt
  commands:
    - glue --version
    - glue-deps list

# NOTE: we deliberatey do NOT include an app entry here, because we instead do this
# in the glueviz meta-package (we don't want glue to appear twice in the navigator)

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
