appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}

travis:
  secure: {BINSTAR_TOKEN: 003PVR0z4wmeuW8OHoEIEDY6R5kZys9VdxctQxQpOP0sz4ovV+jWYcko5mn4pxKyV4rFKu8R5dIkOle9BaE27MWoUcRrU7xxXji3tGXJNYJI4Lq/7/Vve7aXcuGKxQIKp3hKRFd8Hi5Y1YfLLapoR79wb2SmkLTeDw8Thoczf/EQG8lMATRXcy9MnLhvSJA/P8oqndTgdt2ah/bd05q2AxAvO89RIr8ict7kJ3v6jpBQombLqVhB7g7GEP02Kn8FIgKZuXe8l1/13F1dH69XincA0BtlVZVDiNsRR1WZVTpHdj7f0yNad6J9k7gfJCZPGxiJONZlfIAV+PQsqeex/K3yB3dqt473RYID64/WplUKY9aKTauwAMcs4ueRFnyu/jSylfoQs0hnrcu/LlOaJdOE/udzpSQmCRmWuwRbNhs7IWEPCJpUaBnFtoEp3hbAd0z2M+jjKTH7+CXPclyCcwSF+N6vYp9P7dkyQboXbfCWYuPQqSXHnsHbLg0CF1qXBk/VktLUflWKUQyNalghdzlQkASWFZ3ct6f36O1CSjl8YDeEM2OnlLvpYM7lfSYn9020CGGCHXN9Ol6iANR1B6cx1o9gy5G2VT03M5B19rVF7TVPu7yHX4qG1cOcVs63+yRs2ddY5BHWeJXZ7882d9J16ahUcw9I/hCO8SF5V24=}

compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
idle_timeout_minutes: 60
conda_forge_output_validation: true
