build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
idle_timeout_minutes: 60
provider:
  win: azure
test: native_and_emulated
conda_build:
  pkg_format: '2'
